name: SFDX Validate

on: [push]

env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
  CUMULUSCI_SERVICE_connected_app: ${{ secrets.CUMULUSCI_CONNECTED_APP }}
  CUMULUSCI_ORG_demodeploy: ${{ secrets.CUMULUSCI_ORG_DEMODEPLOY }}
  SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
  SFDX_CLIENTID: ${{ secrets.SFDX_CLIENTID }}

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest
    env:
      CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
    - uses: actions/checkout@v2
    - name: Install sfdx
      run: |
        mkdir sfdx
        wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
        ./sfdx/install
        echo ${{ secrets.SFDX_JWT_KEY }} > sfdx_key
        sfdx force:auth:jwt:grant --jwtkeyfile sfdx_key --username $SFDX_USERNAME --clientid $SFDX_CLIENTID
        # echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
        # sfdx force:auth:sfdxurl:store -f sfdx_auth -s
    - name: Validate Source
      run: sfdx force:source:deploy -c -p force-app
    # - name: Set up Python
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: "3.8"
    # - name: Install CumulusCI
    #   run: |
    #     python -m pip install -U pip
    #     pip install cumulusci
    # - run: |
    #     cci flow run my_deploy --org demodeploy