name: SFDX Validate

on: [push]

env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
  CUMULUSCI_SERVICE_connected_app: ${{ secrets.CUMULUSCI_CONNECTED_APP }}
  CUMULUSCI_ORG_demodeploy: ${{ secrets.CUMULUSCI_ORG_DEMODEPLOY }}
  SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
  SFDX_CLIENTID: ${{ secrets.SFDX_CLIENTID }}
  SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY }}

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest
    env:
      CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v2
    # - uses: actions/checkout@v2
    - name: Setup AUth
      run: |
        # mkdir sfdx
        # wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
        # ./sfdx/install
        echo "$SFDX_JWT_KEY" > jwt.key
        sfdx force:auth:jwt:grant --jwtkeyfile jwt.key --username $SFDX_USERNAME --clientid $SFDX_CLIENTID -s
        echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
        sfdx force:auth:sfdxurl:store -f sfdx_auth -s
    - name: Validate Source
      run: sfdx force:source:deploy -c -p force-app
    # - name: Set up Python
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: "3.8"
    # - name: Install CumulusCI
    #   run: |
    #     python -m pip install -U pip
    #     pip install cumulusci
    # - run: |
    #     cci flow run my_deploy --org demodeploy